### ISSUE TITLE
Find way to automatically start/restart Limnoria IRC bot across reboots

### ISSUE THREAD

**Issue by jwflory** [jwflory/infrastructure#11]
Currently, the `irc/limnoria` role only installs all packages and puts configuration files into place. The next step is for me to put something together (a systemd unit file?) to gracefully handle starts, stops, and restarts (e.g. if the bot crashes or the server reboots, the bot should restart automatically).

Anyone have other suggestions or pointers to resources on writing systemd unit files?

**Comment by Tjzabel** [comment]
### Update
@jwflory Found my working service file! Below is a modified template I made from a service file I had to create that needed internet access.
```
[Unit]
Description= # purpose of service
Requires=network.target
After=multi-user.target

[Service]
Type=simple # generally good to keep, can remove this field if you want
ExecStart= # command to start executable/process
Restart=always
RestartSec=60
User= # use this if you want to run the service as a specific user

[Install]
WantedBy=multi-user.target
```

**Comment by jwflory** [comment]
@Tjzabel Not yet. I hit file permission issues when testing in Vagrant and haven't been able to debug further. I need to figure out a standard way to deploy the bots. I want to run the bots as a specific user, but perhaps I need to give up on this approach and use `root`. Not sure what to do yet.
