### ISSUE TITLE
Install yarn through Fedora repository

### ISSUE THREAD

**Issue by Tjzabel** [jwflory/infrastructure#36]
## Synopsis
Yarn can now be installed from the default Fedora repository. This should be updated in the teleirc ansible role. 

#### Links
* [Yarn teleirc install](https://github.com/jwflory/infrastructure/blob/4e54c98526f2ecb5f81bc66b661203088dde6fce/roles/teleirc/tasks/main.yml#L14)

**Comment by jwflory** [comment]
@Tjzabel Thanks for opening this. :smile: I forgot about this since we did it in the Teleirc Docker image. I'll work on this sometime after the new year.

**Comment by jwflory** [comment]
Since this PR was opened, FOSSRIT/infrastructure#20 was improved on. The best place to find a Teleirc role is in the FOSSRIT/infrastructure repo. The Teleirc role was moved out of this repo in #33.

Closing as `wontfix` because of this. In FOSSRIT/infrastructure, the host is a CentOS 7 host.
