### ISSUE TITLE
Service disruption: irc.jwf.io certificate has been expired

### ISSUE THREAD

**Issue by akarshanbiswas** [jwflory/infrastructure#40]
# Summary
The certificate for irc.jwf.io has been expired which is making IRC/chromium unhappy. As we talked on telegram, probably auto renewal script must have failed

* **Urgency**: critical

# Other details
It must be renewed manually for now and maybe find out the reason why auto renewal script failed(?)

**Comment by jwflory** [comment]
I manually renewed the certificate and updated it on the ZNC end. The warning about an expired certificate should now be fixed.

I remembered why I had this issue. The `certbot` package from EPEL was broken for me for some time ([BZ #1689951](https://bugzilla.redhat.com/show_bug.cgi?id=1689951)), but this dependency issue must have been resolved in-between my monthly renewal script running and the package fix. This shouldn't happen again.

Thanks for bringing it to my attention @akarshanbiswas! :+1:
